from pydantic import BaseModel, Field
from typing import List, Optional


class QueryRequest(BaseModel):
    """
    Request schema for querying the RAG system.
    """

    query: str = Field(
        ...,
        description="User question to ask the RAG system",
        example="Summarize the Attention Is All You Need paper"
    )


class Source(BaseModel):
    """
    Represents a document source used in the answer.
    """

    file_name: Optional[str] = Field(
        None,
        description="Source document filename"
    )

    page_number: Optional[int] = Field(
        None,
        description="Page number from the document"
    )


class QueryResponse(BaseModel):
    """
    Response schema returned by the RAG API.
    """

    answer: str = Field(
        ...,
        description="Final answer generated by the LLM"
    )

    sources: List[Source] = Field(
        default_factory=list,
        description="List of document sources used to generate the answer"
    )